spring.application.name=zootopia-ecommerce

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-fragrant-band-a1q0ldxx-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_V4B0LJXrUpZE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth2 Configuration (Hardcoded - Working)
spring.security.oauth2.client.registration.google.client-id=471740377286-cfu3gnhqeah0jd1uuferj7b88pgjbeer.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# JWT Configuration (Extended expiration to 30 days)
jwt.secret=c2498812e739a761de5f101556295e5b4f2884363e0e8c44fa883d58ec5ff1bf7a6082b99b97d220e74c31e7d997eea5442e7c4e406576f9232501cf5047fe30e171d56e36d51a3b4fbb9c5017344285445ba654b46dcca70a1eaf4acbfb6a5f49f098839c9078a28dc79e665be35e6bcd3cd162413150a7cc4255a4968a5018655535412dd24c774a737c5c2416afd8924f99c9322ceb8cd39ded230ce8831f6b517383f28ecc2a9cd7a4606669ebcd854ba9674e88b750e386ff1b3bddceea51b488c26a735896bb146e6b6d71849e35fe5017bc6de0cf1dc86268906ac0851d280d1cc769427bb9f116195ec490708deafbbfc12c8142656c3dffbe77649e
jwt.expiration=2592000000

# PayMongo Configuration (Test Mode)
paymongo.secret-key=sk_test_VGDkQ3MnMuQCcyVM1PqVrsvU
paymongo.public-key=pk_test_xQ6YXcPJv39WdY691P46bvR4

# PayMongo Configuration (Live Mode - Commented out for now)
# paymongo.secret-key=sk_live_GR3PfFsfoUvfoocXiYgUMzBy
# paymongo.public-key=pk_live_bfMPnrEKzoVUcqLbneacJvQc

# Server Configuration
server.port=8080
server.error.include-stacktrace=never

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB